SET SERVEROUTPUT ON
DECLARE
    x NUMBER:= 20;
BEGIN
    IF  x=10 THEN
        DBMS_OUTPUT.PUT_LINE('SS');
    ELSIF x=20 THEN
        DBMS_OUTPUT.PUT_LINE('AAAAAA');
    ELSE
        DBMS_OUTPUT.PUT_LINE('RR');
    END IF;
END;
