SET SERVEROUTPUT ON;

DECLARE
    salario NUMBER;
    NOMBRE EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT 
        SALARY,FIRST_NAME INTO salario,NOMBRE
    FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
    DBMS_OUTPUT.PUT_LINE(salario);
    DBMS_OUTPUT.PUT_LINE(NOMBRE);
END;
